import test from 'node:test';
import assert from 'node:assert/strict';
import {openStore,createTrial} from '../server/store.mjs';
import {sqliteAdapter} from '../cloudflare/sqlite-adapter.js';
import {handleApi} from '../cloudflare/worker.mjs';
import {handleAccountApi,bootstrapAdmin,recoverAdmin,jsonResponse} from '../shared/accounts.js';
import {DEFAULT_PROFILE} from '../shared/core.js';

const password='A-Long-Test-Password-123!';
function fixture(){
  const sqlite=openStore(':memory:'),jobs=[];
  const storage={sql:{exec(query,...values){const stmt=sqlite.prepare(query);const rows=stmt.columns().length?stmt.all(...values):(stmt.run(...values),[]);return {toArray:()=>rows};}},transactionSync(fn){sqlite.exec('BEGIN');try{const result=fn();sqlite.exec('COMMIT');return result;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
  const env={DB:sqliteAdapter(storage),APP_ORIGIN:'https://compass.test',AUTH_PEPPER:'an-auth-pepper-longer-than-thirty-two-characters',LLM_BASE_URL:'https://model.test/v1',LLM_MODEL:'fixture',LLM_API_KEY:'test-key',MAX_CONCURRENT:'2'};
  const ctx={waitUntil(job){jobs.push(job);}};
  const request=(path,body,cookie,origin=env.APP_ORIGIN)=>new Request(env.APP_ORIGIN+path,{method:body?'POST':'GET',headers:{Origin:origin,'cf-connecting-ip':'192.0.2.5',...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  async function call(path,body,cookie,origin){try{return await handleApi(request(path,body,cookie,origin),env,ctx);}catch(error){return jsonResponse({error:error.message},error.status||400);}}
  async function register(name='student_a'){const res=await call('/api/auth/register',{username:name,password,displayName:name,role:'admin'});assert.equal(res.status,200);return {cookie:res.headers.get('set-cookie').split(';')[0],user:(await res.json()).user};}
  async function admin(){const user=await bootstrapAdmin({username:'owner_test',password,displayName:'测试管理员'},env);const res=await call('/api/auth/login',{username:user.username,password});return {cookie:res.headers.get('set-cookie').split(';')[0],user};}
  return {sqlite,env,ctx,jobs,request,call,register,admin,code:()=>createTrial(sqlite),async close(){await Promise.all(jobs);sqlite.close();}};
}
test('registration only grants user role, salts hashes, rotates session and preserves case-insensitive uniqueness',async()=>{const f=fixture();try{const a=await f.register();assert.equal(a.user.role,'user');assert.ok(!JSON.stringify(a.user).includes('password'));const raw=f.sqlite.prepare('SELECT * FROM users').get();assert.notEqual(raw.password_hash,password);assert.equal(raw.password_iterations,100000);assert.equal((await f.call('/api/auth/register',{username:'STUDENT_A',password})).status,409);const bad=await f.call('/api/auth/login',{username:'student_a',password:'Wrong-Password-123'});assert.equal(bad.status,401);const login=await f.call('/api/auth/login',{username:'student_a',password});assert.notEqual(login.headers.get('set-cookie').split(';')[0],a.cookie);assert.ok(login.headers.get('set-cookie').includes('HttpOnly'));}finally{await f.close();}});
test('administrator bootstrap cannot overwrite an existing administrator',async()=>{const f=fixture();try{await f.admin();await assert.rejects(()=>bootstrapAdmin({username:'new_owner',password},f.env),error=>error.status===409);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM users WHERE role='admin'").get().n,1);}finally{await f.close();}});
test('unauthenticated and normal users cannot reach administrator endpoints',async()=>{const f=fixture();try{assert.equal((await f.call('/api/admin/users')).status,401);const a=await f.register();for(const path of ['/api/admin/overview','/api/admin/users','/api/admin/trials'])assert.equal((await f.call(path,null,a.cookie)).status,403);assert.equal((await f.call('/api/admin/users/update',{userId:a.user.id,role:'admin'},a.cookie)).status,403);}finally{await f.close();}});
test('sessions reject cross-origin mutation and logout invalidates the server session',async()=>{const f=fixture();try{const a=await f.register();assert.equal((await f.call('/api/auth/logout',{},a.cookie,'https://evil.test')).status,403);assert.equal((await f.call('/api/auth/logout',{},a.cookie)).status,200);assert.equal((await f.call('/api/user/workspace',null,a.cookie)).status,401);}finally{await f.close();}});
test('workspace identity comes from session, users remain isolated, and revisions prevent overwrite',async()=>{const f=fixture();try{const a=await f.register(),b=await f.register('student_b');const payload={version:2,profile:{...DEFAULT_PROFILE},favorites:[1],tasks:[{id:'my-task',competitionId:1,title:'私人计划',priority:'normal',done:false,due:''}]};assert.equal((await f.call('/api/user/workspace',{revision:0,payload,userId:b.user.id},a.cookie)).status,200);const aData=await(await f.call('/api/user/workspace',null,a.cookie)).json(),bData=await(await f.call('/api/user/workspace',null,b.cookie)).json();assert.equal(aData.payload.tasks[0].title,'私人计划');assert.equal(bData.payload.tasks.length,0);assert.equal((await f.call('/api/user/workspace',{revision:0,payload},a.cookie)).status,409);assert.equal((await f.call('/api/user/workspace',{revision:1,payload:{...payload,favorites:[999999]}},a.cookie)).status,400);}finally{await f.close();}});
test('old card redemption requires login, claims are exclusive and repeat redemption never duplicates quota',async()=>{const f=fixture();try{const a=await f.register(),b=await f.register('student_b'),code=f.code();assert.equal((await f.call('/api/trial/session',{code})).status,401);assert.equal((await f.call('/api/trial/session',{code},a.cookie)).status,200);assert.equal((await f.call('/api/trial/session',{code},a.cookie)).status,200);assert.equal((await f.call('/api/trial/session',{code},b.cookie)).status,409);const cap=await(await f.call('/api/capabilities',null,a.cookie)).json();assert.equal(cap.remaining,3);assert.equal((await(await f.call('/api/capabilities',null,b.cookie)).json()).remaining,0);}finally{await f.close();}});
test('admin grants and card status immediately change account entitlements; deactivation invalidates sessions',async()=>{const f=fixture();try{const owner=await f.admin(),a=await f.register();assert.equal((await f.call('/api/admin/users/update',{userId:a.user.id,dailyGrant:5},owner.cookie)).status,200);assert.equal((await(await f.call('/api/capabilities',null,a.cookie)).json()).remaining,5);const create=await(await f.call('/api/admin/trials/create',{count:2,dailyLimit:3},owner.cookie)).json();await f.call('/api/trial/session',{code:create.codes[0]},a.cookie);assert.equal((await(await f.call('/api/capabilities',null,a.cookie)).json()).remaining,8);const card=f.sqlite.prepare("SELECT id FROM trials WHERE owner_user_id=? AND kind='redeem'").get(a.user.id);await f.call('/api/admin/trials/update',{trialId:card.id,active:0},owner.cookie);assert.equal((await(await f.call('/api/capabilities',null,a.cookie)).json()).remaining,5);await f.call('/api/admin/users/update',{userId:a.user.id,status:'disabled'},owner.cookie);assert.equal((await f.call('/api/user/workspace',null,a.cookie)).status,401);assert.equal((await f.call('/api/auth/login',{username:a.user.username,password})).status,403);}finally{await f.close();}});
test('reset generates one-time temporary password, expires sessions and requires change before private operations',async()=>{const f=fixture();try{const owner=await f.admin(),a=await f.register();const reset=await(await f.call('/api/admin/users/reset-password',{userId:a.user.id},owner.cookie)).json();assert.ok(reset.temporaryPassword.length>20);assert.equal((await f.call('/api/user/workspace',null,a.cookie)).status,401);const login=await f.call('/api/auth/login',{username:a.user.username,password:reset.temporaryPassword});const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await login.json()).user.mustChangePassword,true);assert.equal((await f.call('/api/user/workspace',null,cookie)).status,403);const changed=await f.call('/api/auth/password',{currentPassword:reset.temporaryPassword,newPassword:password},cookie);assert.equal(changed.status,200);assert.equal((await f.call('/api/user/workspace',null,changed.headers.get('set-cookie').split(';')[0])).status,200);assert.equal((await f.call('/api/user/workspace',null,cookie)).status,401);}finally{await f.close();}});
test('administrator cannot disable self or remove last usable administrator',async()=>{const f=fixture();try{const owner=await f.admin();assert.equal((await f.call('/api/admin/users/update',{userId:owner.user.id,status:'disabled'},owner.cookie)).status,400);assert.equal((await f.call('/api/admin/users/update',{userId:owner.user.id,role:'user'},owner.cookie)).status,400);const list=await(await f.call('/api/admin/users',null,owner.cookie)).json();assert.ok(!JSON.stringify(list).includes('password_hash'));assert.ok(!JSON.stringify(list).includes('password_salt'));}finally{await f.close();}});
test('bound card drives generation and account request replay remains idempotent',async()=>{const f=fixture();try{const a=await f.register();await f.call('/api/trial/session',{code:f.code()},a.cookie);let count=0;f.env.UPSTREAM_FETCH=async(_url,options)=>{count++;const input=JSON.parse(JSON.parse(options.body).messages[1].content),id=input.candidates[0].id;return Response.json({choices:[{message:{content:JSON.stringify({summary:'账号生成测试',recommendations:[{competitionId:id,role:'main',reason:'相关方向',gaps:[],pending:[]}],weeks:[1,2,3,4].map(week=>({week,tasks:[{competitionId:id,title:'准备任务',hours:1}]}))})}}]});};const body={requestId:'account_request_1',profile:{...DEFAULT_PROFILE,interests:['code']}};const first=await f.call('/api/plans/generate',body,a.cookie);assert.ok((await first.text()).includes('"type":"result"'));await Promise.all(f.jobs);const replay=await f.call('/api/plans/generate',body,a.cookie);assert.ok((await replay.text()).includes('"replayed":true'));assert.equal(count,1);assert.equal((await(await f.call('/api/capabilities',null,a.cookie)).json()).remaining,2);}finally{await f.close();}});
test('password change invalidates other sessions while keeping current device signed in',async()=>{const f=fixture();try{const a=await f.register(),other=await f.call('/api/auth/login',{username:a.user.username,password});const second=other.headers.get('set-cookie').split(';')[0];const changed=await f.call('/api/auth/password',{currentPassword:password,newPassword:'Another-Long-Password-456'},a.cookie);assert.equal(changed.status,200);assert.equal((await f.call('/api/user/workspace',null,second)).status,401);assert.equal((await f.call('/api/auth/login',{username:a.user.username,password})).status,401);}finally{await f.close();}});
test('repeated failed logins are rate limited without granting a session',async()=>{const f=fixture();try{await f.register();for(let i=0;i<10;i++)assert.equal((await f.call('/api/auth/login',{username:'student_a',password:'wrong-password-123'})).status,401);assert.equal((await f.call('/api/auth/login',{username:'student_a',password})).status,429);}finally{await f.close();}});
test('deployment-level recovery only recovers an existing admin and invalidates old sessions',async()=>{const f=fixture();try{const owner=await f.admin(),a=await f.register();await assert.rejects(()=>recoverAdmin({username:a.user.username,password},f.env),error=>error.status===404);const fresh='Recovery-Password-Long-456';await recoverAdmin({username:owner.user.username,password:fresh},f.env);assert.equal((await f.call('/api/admin/users',null,owner.cookie)).status,401);const login=await f.call('/api/auth/login',{username:owner.user.username,password:fresh});assert.equal(login.status,200);}finally{await f.close();}});
